# Generated by Django 4.0.3 on 2023-07-22 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 1, 34, 25, 55926)),
        ),
    ]
