# Generated by Django 4.0.3 on 2023-07-23 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 23, 13, 55, 14, 759602)),
        ),
    ]
